import "./globals.css";
import Bar from "@/components/AdminBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {

  return (
    <html lang={"ru"}>
      <body className="bg-[#FFAB08]">
          <Bar />
          {children}
      </body>
    </html>
  );
}
