
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {

  return (
    <html lang={"ru"}>
      <body className="bg-[#FFAB08]">
        <h1>Layout</h1>
          {children}
      </body>
    </html>
  );
}
